### ISSUE TITLE
Installing this plugin breaks the sitemap

### ISSUE THREAD

**Issue by rosie607** [concrete5-community-store/community_store_abandoned_cart#2]
Hi there
When I install this package I get the following error on my /dashboard/sitemap/full page.
`Load error! (SyntaxError: Unexpected token < in JSON at position 0)`
Issue is resolved if I uninstall package.

**Comment by Jozzeh** [comment]
Hi,  
Thank you for submitting the issue.   
I've committed a change in the controller so the error does not occur again.  
Please update your package to **version 0.0.9** .  

_For future reference_ :  
In the controller, I loaded a javascript file on each page. This javascript file also loaded with the json result of the fancetree.js (sitemap visualisation). I've changed the controller to load the javascript only when the URL is /checkout.

**Comment by rosie607** [comment]
Excellent, thanks :-)
