### ISSUE TITLE
Cron Jobs

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store_abandoned_cart#4]
I did not get the Abandoned Cart reminder notification, checked my cron jobs and got nothing there, should it have installed the cron itself, or do I need to set it up? I am using cPanel.

**Comment by Jozzeh** [comment]
The abandoned cart module works by creating an automated job in Concrete5.  
It does not activate that automated job (cron job). That is the responsibility of the developer.  
 

**Within Concrete5** :  
Login and go to "Dashboard" -> ''System and Settings" -> "Automated jobs"  
(index.php/dashboard/system/optimization/jobs)  

You should see a job with the name 'Send Abandoned Cart Mails' .  
That is the job that sends the abandoned cart e-mail ... My advice is to run it every 15-30 minutes, but you can choose to run it only once or twice a day.     

Link to the Concrete5 editor docs about automated jobs :  
https://documentation.concrete5.org/editors/dashboard/system-and-maintenance/jobs/automated-jobs

**Comment by mdius** [comment]
Yeah, now I know how to set it up now. It was simple.
Thank you!
