### ISSUE TITLE
BCC Request

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store_abandoned_cart#5]
Hello, I love this add-on, I just wish there was a way to receive a blind carbon copy of the abandoned order with maybe only with the acData info and email address? To see if there is a theme to what products are being dumped and our sales team could reach out to them 1 time to see if we can offer an intensive to complete an order.

**Comment by Jozzeh** [comment]
Hi, I'm glad to read you enjoy the add-on.  
Give me some time to insert this feature in the abandoned cart add-on... it's a good idea.

**Comment by Jozzeh** [comment]
I have updated the package and tested it locally. However I cannot receive mails from my local host.   
There are 2 new settings : copy email address and copy subject.   
It's not a blind copy mail, but just an extra mail that is send to an email address.  
The content of that mail is the user data (email and username) and the abandoned products.

**Please test this version first before implementing it on a live website.**

**Comment by mdius** [comment]
Thank you!
I have not been able to test this yet, I have to redo my test site again. Should be up and running tomorrow, then I'll test it and let you know.

**Comment by mdius** [comment]
That is perfect! Better than a Blind Carbon Copy!
I tested it on my test site and implemented it, it seems to be working perfectly.

**Comment by Jozzeh** [comment]
Glad it works.  
Maybe in the future, I (or someone else) could add an extra dashboard page that shows some graphs / analytics of the abandoned carts. However, to have some decent analytics, the products in cart should be stored much sooner and more frequent ....   

But for now, I'll close this issue.
